services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  backend:
    image: ghcr.io/farooq-dev00/three-tier-app-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb

  frontend:
    image: ghcr.io/farooq-dev00/three-tier-app-frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
